# Generated by Django 6.0.4 on 2026-05-17 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('asset_type', models.CharField(choices=[('equipment', 'Equipment'), ('consumable', 'Consumable')], max_length=20)),
                ('category', models.CharField(max_length=50)),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('quantity', models.PositiveIntegerField()),
                ('status', models.CharField(max_length=50)),
                ('log_details', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Asset',
                'verbose_name_plural': 'Assets',
            },
        ),
        migrations.CreateModel(
            name='SystemConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system_name', models.CharField(default='RAYMART Asset Management System', help_text='The name of your system', max_length=200)),
                ('version', models.CharField(default='1.0.0', help_text='Current system version', max_length=50)),
                ('description', models.TextField(default='A comprehensive solution for managing company assets efficiently', help_text='System description displayed on homepage')),
                ('features', models.TextField(default='Real-time asset tracking\nUser management\nAsset categorization\nInventory valuation\nAdmin dashboard', help_text='Key features (one per line)')),
                ('founded', models.CharField(default='2026', help_text='Year or date founded', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'System Configuration',
                'verbose_name_plural': 'System Configuration',
            },
        ),
    ]
