# Generated by Django 6.0.4 on 2026-06-13 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('audit_assets', 'Can Audit Assets'), ('request_asset', 'Can Request Asset'), ('approve_request', 'Can Approve Request'),('view_dashboard', 'Can View Dashboard')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
    ]
