# Generated by Django 6.0.4 on 2026-05-14 05:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField()),
                ('ordered_at', models.DateTimeField()),
                ('waiter', models.CharField(max_length=100)),
                ('is_discounted', models.BooleanField(default=False)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.menuitem')),
            ],
        ),
    ]
