# Generated by Django 6.0.4 on 2026-06-22 05:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('assets', '0002_alter_asset_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profile',
            options={'permissions': [('view_back_to_users', 'Can View Back to Users Button')]},
        ),
    ]
