# Generated by Django 6.0.4 on 2026-06-13 05:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_assetlog_cost_per_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='asset',
            options={'permissions': [('view_reports', 'Can View Reports'), ('audit_assets', 'Can Audit Assets'), ('manage_inventory', 'Can Manage Inventory'), ('request_asset', 'Can Request Asset'), ('approve_request', 'Can Approve Request')], 'verbose_name': 'Asset', 'verbose_name_plural': 'Assets'},
        ),
        migrations.AlterModelOptions(
            name='assetrequest',
            options={'permissions': [('view_pending_requests', 'Can View Pending Request Table'), ('view_request_history', 'Can View Request History Table')]},
        ),
    ]
