# Generated by Django 6.0.4 on 2026-05-23 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('ADMIN', 'Administrator'), ('EXEC', 'Executive'), ('STAFF', 'Staff')], max_length=50, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
    ]
