# Generated by Django 6.0.4 on 2026-05-24 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0004_alter_role_description_alter_role_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('EXEC', 'Executive'), ('STAFF', 'Staff Member')], default='ADMIN', max_length=50),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
