# Generated by Django 6.0.4 on 2026-05-24 10:52

from django.db import migrations, models


def assign_unique_codes(apps, schema_editor):
    Role = apps.get_model('roles', 'Role')
    
    # Assign unique codes based on role names
    code_mapping = {
        'ADMINISTRATOR': 'ADMIN',
        'EXECUTIVE': 'EXEC',
        'STAFF': 'STAFF',
    }
    
    for role in Role.objects.all():
        new_code = code_mapping.get(role.name, role.name[:5].upper())
        Role.objects.filter(pk=role.pk).update(code=new_code)


def reverse_assign_codes(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_role_options_role_code_alter_role_name'),
    ]

    operations = [
        migrations.RunPython(assign_unique_codes, reverse_assign_codes),
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(max_length=50),
        ),
    ]
