# Generated by Django 6.0.4 on 2026-05-24 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0005_alter_role_options_role_code_alter_role_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='code',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('EXEC', 'Executive'), ('STAFF', 'Staff Member')], default='ADMIN', max_length=50, unique=True),
        ),
    ]
