# Generated by Django 6.0.4 on 2026-05-17 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ContentPage',
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='hero_image',
            field=models.ImageField(blank=True, help_text='Hero section image displayed on homepage (right side box)', null=True, upload_to='hero/'),
        ),
    ]
