# Generated by Django 6.0.4 on 2026-05-17 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_delete_contentpage_systemconfig_hero_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='hero_subtitle',
            field=models.TextField(default='Streamline your asset tracking, enhance inventory control, and maximize operational efficiency with our comprehensive platform designed for modern businesses.', help_text='Subtitle/description for hero section'),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='hero_title',
            field=models.CharField(default='Asset Management that makes a difference', help_text='Main headline for hero section', max_length=200),
        ),
    ]
