# Generated by Django 6.0.4 on 2026-05-17 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_systemconfig_hero_subtitle_systemconfig_hero_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('icon', models.CharField(choices=[('bi-lightning', 'Lightning (Real-time)'), ('bi-shield-check', 'Shield (Security)'), ('bi-graph-up', 'Graph (Analytics)'), ('bi-person-check', 'Person (User)'), ('bi-layers', 'Layers (Organization)'), ('bi-headset', 'Headset (Support)'), ('bi-gear', 'Gear (Settings)'), ('bi-lock', 'Lock (Protection)'), ('bi-database', 'Database (Data)'), ('bi-speedometer', 'Speedometer (Performance)')], default='bi-lightning', help_text='Icon from Bootstrap Icons', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Order in which features appear (0-5)')),
                ('is_active', models.BooleanField(default=True, help_text='Show/hide this feature')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Feature',
                'verbose_name_plural': 'Features',
                'ordering': ['order'],
            },
        ),
    ]
