# Generated by Django 6.0.4 on 2026-05-17 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_feature'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='hero_background_color',
            field=models.CharField(default='#8a1538', help_text='Hero section background color (hex code, e.g., #8a1538)', max_length=7),
        ),
        migrations.AddField(
            model_name='systemconfig',
            name='hero_background_image',
            field=models.ImageField(blank=True, help_text='Hero section background image (optional, will override background color)', null=True, upload_to='hero/backgrounds/'),
        ),
    ]
