# Generated by Django 6.0.4 on 2026-05-17 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_systemconfig_hero_background_color_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='metrics_section_title',
            field=models.CharField(default='Key Metrics', help_text='Title for the Key Metrics section on homepage', max_length=200),
        ),
    ]
