# Generated by Django 6.0.4 on 2026-05-17 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0006_systemconfig_metrics_section_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfig',
            name='recent_assets_section_title',
            field=models.CharField(default='Recent Assets', help_text='Title for the Recent Assets section on homepage', max_length=200),
        ),
    ]
